CREATE DATABASE ReportService
COLLATE Cyrillic_General_100_CI_AI
GO

USE ReportService
GO

CREATE TABLE Users(
Id INT PRIMARY KEY IDENTITY,
Username NVARCHAR(30) NOT NULL,
Password NVARCHAR(50) NOT NULL,
Name NVARCHAR(50),
Gender CHAR(1),
BirthDate DATETIME,
Age INT,
Email NVARCHAR(50) NOT NULL
)
GO

ALTER TABLE Users
ADD CONSTRAINT ch_Users_Gender
CHECK(Gender in ('M', 'F'))
GO

ALTER TABLE Users
ADD CONSTRAINT uq_Users_Username
UNIQUE (Username)
GO

CREATE TABLE Departments(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Employees(
Id INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR(25),
LastName NVARCHAR(25),
Gender CHAR(1),
BirthDate DATETIME,
Age INT,
DepartmentId INT NOT NULL FOREIGN KEY REFERENCES Departments(Id)
)
GO

ALTER TABLE Employees
ADD CONSTRAINT ch_Employees_Gender
CHECK(Gender in ('M', 'F'))
GO

CREATE TABLE Categories(
Id INT PRIMARY KEY IDENTITY,
Name VARCHAR(50) NOT NULL,
DepartmentId INT FOREIGN KEY REFERENCES Departments(Id)
)
GO

CREATE TABLE Status(
Id INT PRIMARY KEY IDENTITY,
Label VARCHAR(30) NOT NULL
)
GO

CREATE TABLE Reports(
Id INT PRIMARY KEY IDENTITY,
CategoryId INT NOT NULL FOREIGN KEY REFERENCES Categories(Id),
StatusId INT NOT NULL FOREIGN KEY REFERENCES Status(Id),
OpenDate DATETIME NOT NULL,
CloseDate DATETIME,
Description VARCHAR(200),
UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
EmployeeId INT FOREIGN KEY REFERENCES Employees(Id)
)