CREATE DATABASE OnlineStore
COLLATE Cyrillic_General_100_CI_AI
GO

USE OnlineStore
GO

CREATE TABLE Cities(
CityID INT PRIMARY KEY IDENTITY,
Name VARCHAR(50) NOT NULL
) 
GO

CREATE TABLE Customers(
CustomerID INT PRIMARY KEY IDENTITY,
Name VARCHAR(50) NOT NULL,
Birthday DATE,
CityID INT FOREIGN KEY REFERENCES Cities(CityID)
)
GO

CREATE TABLE Orders(
OrderID INT PRIMARY KEY IDENTITY,
CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerID)
)
GO

CREATE TABLE ItemTypes(
ItemTypeID INT PRIMARY KEY IDENTITY,
Name VARCHAR(50) NOT NULL
)
GO

CREATE TABLE Items(
ItemID INT PRIMARY KEY IDENTITY,
Name VARCHAR(50) NOT NULL,
ItemTypeID INT FOREIGN KEY REFERENCES ItemTypes(ItemTypeID)
)
GO

CREATE TABLE OrderItems(
OrderID INT FOREIGN KEY REFERENCES Orders(OrderID),
ItemID INT FOREIGN KEY REFERENCES Items(ItemID)

CONSTRAINT PK_OrderItems_OrderID_ItemID
PRIMARY KEY(OrderID, ItemID)
)