CREATE DATABASE University
COLLATE Cyrillic_General_100_CI_AI
GO

USE University
GO

CREATE TABLE Majors(
MajorID INT PRIMARY KEY IDENTITY,
Name NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Students(
StudentID INT PRIMARY KEY IDENTITY,
StudentNumber VARCHAR(50) NOT NULL,
StudentName NVARCHAR(50) NOT NULL,
MajorID INT FOREIGN KEY REFERENCES Majors(MajorID)
)
GO

CREATE TABLE Payments(
PaymentID INT PRIMARY KEY IDENTITY,
PaymentDate DATE NOT NULL,
PaymentAmount DECIMAL(15, 2) NOT NULL,
StudentID INT FOREIGN KEY REFERENCES Students(StudentID)
)
GO

CREATE TABLE Subjects(
SubjectID INT PRIMARY KEY IDENTITY,
SubjectName NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Agenda(
StudentID INT FOREIGN KEY REFERENCES Students(StudentID),
SubjectID INT FOREIGN KEY REFERENCES Subjects(SubjectID)

CONSTRAINT PK_Agenda_StudentID_SubjectID
PRIMARY KEY(StudentID, SubjectID)
)