CREATE DATABASE RentACar
COLLATE Cyrillic_General_100_CI_AI
GO

USE RentACar
GO

CREATE TABLE Clients(
Id INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR(30) NOT NULL,
LastName NVARCHAR(30) NOT NULL,
Gender CHAR(1),
BirthDate DATETIME,
CreditCard NVARCHAR(30) NOT NULL,
CardValidity DATETIME,
Email NVARCHAR(50) NOT NULL
)
GO

ALTER TABLE Clients
ADD CONSTRAINT ch_Clients_Gender
CHECK (Gender IN ('M', 'F'))
GO

CREATE TABLE Towns(
Id INT PRIMARY KEY IDENTITY, 
Name NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Offices(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(40),
ParkingPlaces INT,
TownId INT NOT NULL FOREIGN KEY REFERENCES Towns(Id)
)
GO

CREATE TABLE Models(
Id INT PRIMARY KEY IDENTITY,
Manufacturer NVARCHAR(50) NOT NULL,
Model NVARCHAR(50) NOT NULL,
ProductionYear DATETIME,
Seats INT,
Class NVARCHAR(10),
Consumption DECIMAL(14, 2)
)
GO

CREATE TABLE Vehicles(
Id INT PRIMARY KEY IDENTITY,
ModelId INT NOT NULL FOREIGN KEY REFERENCES Models(Id),
OfficeId INT NOT NULL FOREIGN KEY REFERENCES Offices(Id),
Mileage INT
)
GO

CREATE TABLE Orders(
Id INT PRIMARY KEY IDENTITY, 
ClientId INT NOT NULL FOREIGN KEY REFERENCES Clients(Id),
TownId INT NOT NULL FOREIGN KEY REFERENCES Towns(Id),
VehicleId INT NOT NULL FOREIGN KEY REFERENCES Vehicles(Id),
CollectionDate DATETIME NOT NULL,
CollectionOfficeId INT NOT NULL FOREIGN KEY REFERENCES Offices(Id),
ReturnDate DATETIME,
ReturnOfficeId INT FOREIGN KEY REFERENCES Offices(Id),
Bill DECIMAL(14, 2),
TotalMileage INT
)
GO

